version: '2'

services:
  db:
    image: mongo:4.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: sadarfd23r23rdasd
      MONGO_INITDB_DATABASE: jsshell

  web:
    build: .
    command: python manage.py web
    ports:
      - "5000:5000"
    volumes:
    - '.:/app/'
    depends_on:
      - db

  shell:
    build: .
    environment:
      PYTHONUNBUFFERED: 1
      TERM: xterm-256color
    command: python manage.py shell
    stdin_open: true
    volumes:
    - '.:/app/'
    depends_on:
      - db
      - web
